config/routes.rb
Rails.application.routes.draw do
  resources :ques

  resources :questionnaires

  resources :courses

  devise_for :users

  resources :aspects

  get 'principal/index'

  resources :survey_types

  resources :surveys

  resources :questions

  resources :users

  root 'principal#index'

  get 'load_user' => 'load_user#index'

  post 'load_user' => 'load_user#load_data'

end

app/models/que.rb
class Que
  include Mongoid::Document
  field :type, type: String
  field :q1, type: String
  field :q2, type: String
  field :q3, type: String
  field :q4, type: String
  field :q5, type: String
  field :q6, type: String
  field :q7, type: String
  field :q8, type: String
  field :q9, type: String
  field :q10, type: String
  field :q11, type: String
  field :q12, type: String
  field :q13, type: String
  field :q14, type: String
  field :q15, type: String
  field :q16, type: String
  field :q17, type: String
  field :q18, type: String
  field :q19, type: String
  field :q20, type: String
  field :q21, type: String
  field :q22, type: String
  field :q23, type: String
  field :q24, type: String
  field :q25, type: String
  field :q26, type: String
  field :q27, type: String

  field :totalScore, type: String
  field :knowledge, type: String
  field :methodology, type: String
  field :bonds, type: String
  field :labors, type: String
end

app/controllers/ques_controller.rb
class QuesController < ApplicationController
  before_action :set_que, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    #en este if se tienen en cuenta todas las ips publicas de la universidad de caldas
    
      @permitido="y"
      @ques = Que.all
      respond_with(@ques)
    
      
    
  end

  def show
    respond_with(@que)
  end

  def new
    @que = Que.new
    respond_with(@que)
  end

  def edit
  end

  def create
    @que = Que.new(que_params)
    
    type=@que.type
    if type == "Student"
      questions= [@que.q1,
              @que.q2,
              @que.q3,
              @que.q4,
              @que.q5,
              @que.q6,
              @que.q7,
              @que.q8,
              @que.q9,
              @que.q10,
              @que.q11,
              @que.q12,
              @que.q13,
              @que.q14,
              @que.q15,
              @que.q16,
              @que.q17,
              @que.q18,
              @que.q19,
              @que.q20,
              @que.q21,
              @que.q22,
              @que.q23,
              @que.q24,
              @que.q25,
              @que.q26,
              @que.q27
          ]
    totalScore = 0.0
    knowledge = 0.0
    methodology = 0.0
    bonds = 0.0
    
    for i in 0..3
      if questions[i]=="E"
        totalScore= totalScore + 5.0
        knowledge= knowledge + 5.0
      elsif questions[i]=="B"
        totalScore= totalScore + 4.2
        knowledge= knowledge + 4.2
      elsif questions[i]=="R"
        totalScore= totalScore + 3.0
        knowledge= knowledge + 3.0
      elsif questions[i]=="M"
        totalScore= totalScore + 2.5   
        knowledge= knowledge + 2.5
      end
      
    end

    for i in 4..21
      if questions[i]=="E"
        totalScore= totalScore + 5.0
        methodology= methodology + 5.0
      elsif questions[i]=="B"
        totalScore= totalScore + 4.2
        methodology= methodology + 4.2
      elsif questions[i]=="R"
        totalScore= totalScore + 3.0
        methodology= methodology + 3.0
      elsif questions[i]=="M"
        totalScore= totalScore + 2.5   
        methodology= methodology + 2.5
      end
    end

    for i in 22..26
      if questions[i]=="E"
        totalScore= totalScore + 5.0
        bonds= bonds + 5.0
      elsif questions[i]=="B"
        totalScore= totalScore + 4.2
        bonds= bonds + 4.2
      elsif questions[i]=="R"
        totalScore= totalScore + 3.0
        bonds= bonds + 3.0
      elsif questions[i]=="M"
        totalScore= totalScore + 2.5   
        bonds= bonds + 2.5
      end
    end

    @que2 = Que.new()

    @que2.type=@que.type
    @que2.q1=@que.q1
    @que2.q2=@que.q2
    @que2.q3=@que.q3
    @que2.q4=@que.q4
    @que2.q5=@que.q5
    @que2.q6=@que.q6
    @que2.q7=@que.q7
    @que2.q8=@que.q8
    @que2.q9=@que.q9
    @que2.q10=@que.q10
    @que2.q11=@que.q11
    @que2.q12=@que.q12
    @que2.q13=@que.q13
    @que2.q14=@que.q14
    @que2.q15=@que.q15
    @que2.q16=@que.q16
    @que2.q17=@que.q17
    @que2.q18=@que.q18
    @que2.q19=@que.q19
    @que2.q20=@que.q20
    @que2.q21=@que.q21
    @que2.q22=@que.q22
    @que2.q23=@que.q23
    @que2.q24=@que.q24
    @que2.q25=@que.q25
    @que2.q26=@que.q26
    @que2.q27=@que.q27
    @que2.knowledge=knowledge.to_s
    @que2.totalScore=totalScore.to_s
    @que2.methodology=methodology.to_s
    @que2.bonds=bonds.to_s
    @que2.labors=""
    @que2.save
    respond_with(@que2)

    elsif type == "Director"
      questions= [@que.q1,
              @que.q2,
              @que.q3,
              @que.q4,
              @que.q5,
              @que.q6,
              @que.q7,
              @que.q8,
              @que.q9,
              @que.q10,
              @que.q11,
              @que.q12,
              @que.q13,
              @que.q14,
              @que.q15,
              @que.q16,
              @que.q17,
              @que.q18,
              @que.q19,
              @que.q20,
              @que.q21,
              @que.q22,
              @que.q23,
              @que.q24,
              @que.q25
          ]
    totalScore = 0.0
    knowledge = 0.0
    methodology = 0.0
    labors = 0.0
    bonds = 0.0
    for i in 0..3
      if questions[i]=="E"
        totalScore= totalScore + 5.0
        knowledge= knowledge + 5.0
      elsif questions[i]=="B"
        totalScore= totalScore + 4.375
        knowledge= knowledge + 4.375
      elsif questions[i]=="R"
        totalScore= totalScore + 3.75
        knowledge= knowledge + 3.75
      elsif questions[i]=="M"
        totalScore= totalScore + 3.125  
        knowledge= knowledge + 3.125
      end
    end

    for i in 4..11
      if questions[i]=="E"
        totalScore= totalScore + 2.5
        methodology= methodology + 2.5
      elsif questions[i]=="B"
        totalScore= totalScore + 2.188
        methodology= methodology + 2.188
      elsif questions[i]=="R"
        totalScore= totalScore + 1.875
        methodology= methodology + 1.875
      elsif questions[i]=="M"
        totalScore= totalScore + 1.56  
        methodology= methodology + 1.46
      end
    end

    for i in 12..20
      if questions[i]=="E"
        totalScore= totalScore + 2.22
        labors= labors + 2.22
      elsif questions[i]=="B"
        totalScore= totalScore + 1.95
        labors= labors + 1.95
      elsif questions[i]=="R"
        totalScore= totalScore + 1.67
        labors= labors + 1.67
      elsif questions[i]=="M"
        totalScore= totalScore + 1.39
        labors= labors + 1.39
      end
    end

    for i in 21..24
      if questions[i]=="E"
        totalScore= totalScore + 2.5
        bonds= bonds + 2.5
      elsif questions[i]=="B"
        totalScore= totalScore + 2.4
        bonds= bonds + 2.4
      elsif questions[i]=="R"
        totalScore= totalScore + 1.88
        bonds= bonds + 1.88
      elsif questions[i]=="M"
        totalScore= totalScore + 1.57
        bonds= bonds + 1.57
      end
    end

    @que2 = Que.new()

    @que2.type=@que.type
    @que2.q1=@que.q1
    @que2.q2=@que.q2
    @que2.q3=@que.q3
    @que2.q4=@que.q4
    @que2.q5=@que.q5
    @que2.q6=@que.q6
    @que2.q7=@que.q7
    @que2.q8=@que.q8
    @que2.q9=@que.q9
    @que2.q10=@que.q10
    @que2.q11=@que.q11
    @que2.q12=@que.q12
    @que2.q13=@que.q13
    @que2.q14=@que.q14
    @que2.q15=@que.q15
    @que2.q16=@que.q16
    @que2.q17=@que.q17
    @que2.q18=@que.q18
    @que2.q19=@que.q19
    @que2.q20=@que.q20
    @que2.q21=@que.q21
    @que2.q22=@que.q22
    @que2.q23=@que.q23
    @que2.q24=@que.q24
    @que2.q25=@que.q25
    @que2.knowledge=knowledge.to_s
    @que2.totalScore=totalScore.to_s
    @que2.methodology=methodology.to_s
    @que2.bonds=bonds.to_s
    @que2.labors=labors.to_s
    @que2.save
    respond_with(@que2)
      
    elsif type == "Dean"
      questions= [@que.q1,
              @que.q2,
              @que.q3,
              @que.q4,
              @que.q5,
              @que.q6,
              @que.q7,
              @que.q8,
              @que.q9,
              @que.q10,
              @que.q11,
              @que.q12,
              @que.q13,
              @que.q14,
              @que.q15
          ]
    totalScore = 0.0
    labors = 0.0
    bonds = 0.0
    for i in 0..questions.length
      totalScore= totalScore + questions[i].to_f
    end

    for i in 0..7
      if questions[i]=="E"
        totalScore= totalScore + 5.0
        labors= labors + 5.0
      elsif questions[i]=="B"
        totalScore= totalScore + 4.375
        labors= labors + 4.375
      elsif questions[i]=="R"
        totalScore= totalScore + 3.75
        labors= labors + 3.75
      elsif questions[i]=="M"
        totalScore= totalScore + 3.13
        labors= labors + 3.13
      end
    end

    for i in 8..14
      if questions[i]=="E"
        totalScore= totalScore + 2.86
        bonds= bonds + 2.86
      elsif questions[i]=="B"
        totalScore= totalScore + 2.5
        bonds= bonds + 2.5
      elsif questions[i]=="R"
        totalScore= totalScore + 2.14
        bonds= bonds + 2.14
      elsif questions[i]=="M"
        totalScore= totalScore + 1.71
        bonds= bonds + 1.71
      end
    end

    @que2 = Que.new()

    @que2.type=@que.type
    @que2.q1=@que.q1
    @que2.q2=@que.q2
    @que2.q3=@que.q3
    @que2.q4=@que.q4
    @que2.q5=@que.q5
    @que2.q6=@que.q6
    @que2.q7=@que.q7
    @que2.q8=@que.q8
    @que2.q9=@que.q9
    @que2.q10=@que.q10
    @que2.q11=@que.q11
    @que2.q12=@que.q12
    @que2.q13=@que.q13
    @que2.q14=@que.q14
    @que2.q15=@que.q15
    @que2.knowledge=""
    @que2.totalScore=totalScore.to_s
    @que2.methodology=""
    @que2.bonds=bonds.to_s
    @que2.labors=labors.to_s
    @que2.save
    respond_with(@que2)
      
    else
      @que.save
      respond_with(@que)
    end
  end

  def update
    @que.update(que_params)
    respond_with(@que)
  end

  def destroy
    @que.destroy
    respond_with(@que)
  end

  private
    def set_que
      @que = Que.find(params[:id])
    end

    def que_params
      params.require(:que).permit(:type, :q1,:q2, :q3, :q4,:q5,:q6, :q7, :q8,:q9, :q10, :q11, :q12,:q13, :q14, :q15, :q16,:q17, :q18, :q19,:q20, :q21, :q22, :q23,:q24, :q25, :q26, :q27)
      
    end
end

app/helpers/ques_helper.rb
module QuesHelper
end

app/views/ques/_form.html.erb
<%= form_for(@que) do |f| %>
  <% if @que.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@que.errors.count, "error") %> prohibited this que from being saved:</h2>

      <ul>
      <% @que.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <% if current_user.role_ids.join(",")=="546964bd53525234ef060000" #dean%>
       <div class="field">
         <%= f.hidden_field :type, :value => "Dean" %>
       </div>           
  <% end %> 
  <% if current_user.role_ids.join(",")=="546964bd53525234ef080000" #dir prog%>
          <div class="field">
            <%= f.hidden_field :type, :value => "Director" %>
          </div>       
  <% end %> 
  
  <div class="field">
    <%= f.label :q1 %>
    <%= f.select :q1, options_for_select([["E", "E"], ["B", "B"],["R", "R"],["M", "M"]]) %>
  </div>
  <div class="field">
    <%= f.label :q2 %>
    <%= f.select :q2, options_for_select([["E", "E"], ["B", "B"],["R", "R"],["M", "M"]]) %>
  </div>
  <div class="field">
    <%= f.label :q3 %>
    <%= f.select :q3, options_for_select([["E", "E"], ["B", "B"],["R", "R"],["M", "M"]]) %>
  </div>
  <div class="field">
    <%= f.label :q4 %>
    <%= f.select :q4, options_for_select([["E", "E"], ["B", "B"],["R", "R"],["M", "M"]]) %>
  </div>
  <div class="field">
    <%= f.label :q5 %>
    <%= f.select :q5, options_for_select([["E", "E"], ["B", "B"],["R", "R"],["M", "M"]]) %>
  </div>
  <div class="field">
    <%= f.label :q6 %>
    <%= f.select :q6, options_for_select([["E", "E"], ["B", "B"],["R", "R"],["M", "M"]]) %>
  </div>
  <div class="field">
    <%= f.label :q7 %>
    <%= f.select :q7, options_for_select([["E", "E"], ["B", "B"],["R", "R"],["M", "M"]]) %>
  </div>
  <div class="field">
    <%= f.label :q8 %>
    <%= f.select :q8, options_for_select([["E", "E"], ["B", "B"],["R", "R"],["M", "M"]]) %>
  </div>
  <div class="field">
    <%= f.label :q9 %>
    <%= f.select :q9, options_for_select([["E", "E"], ["B", "B"],["R", "R"],["M", "M"]]) %>
  </div>
  <div class="field">
    <%= f.label :q10 %>
    <%= f.select :q10, options_for_select([["E", "E"], ["B", "B"],["R", "R"],["M", "M"]]) %>
  </div>
  <div class="field">
    <%= f.label :q11 %>
    <%= f.select :q11, options_for_select([["E", "E"], ["B", "B"],["R", "R"],["M", "M"]]) %>
  </div>
  <div class="field">
    <%= f.label :q12 %>
    <%= f.select :q12, options_for_select([["E", "E"], ["B", "B"],["R", "R"],["M", "M"]]) %>
  </div>
  <div class="field">
    <%= f.label :q13 %>
    <%= f.select :q13, options_for_select([["E", "E"], ["B", "B"],["R", "R"],["M", "M"]]) %>
  </div>
  <div class="field">
    <%= f.label :q14 %>
    <%= f.select :q14, options_for_select([["E", "E"], ["B", "B"],["R", "R"],["M", "M"]]) %>
  </div>
  <div class="field">
    <%= f.label :q15 %>
    <%= f.select :q15, options_for_select([["E", "E"], ["B", "B"],["R", "R"],["M", "M"]]) %>
  </div>
  <div class="field">
    <%= f.label :q16 %>
    <%= f.select :q16, options_for_select([["E", "E"], ["B", "B"],["R", "R"],["M", "M"]]) %>
  </div>
  <div class="field">
    <%= f.label :q17 %>
    <%= f.select :q17, options_for_select([["E", "E"], ["B", "B"],["R", "R"],["M", "M"]]) %>
  </div>
  <div class="field">
    <%= f.label :q18 %>
    <%= f.select :q18, options_for_select([["E", "E"], ["B", "B"],["R", "R"],["M", "M"]]) %>
  </div>
  <div class="field">
    <%= f.label :q19 %>
    <%= f.select :q19, options_for_select([["E", "E"], ["B", "B"],["R", "R"],["M", "M"]]) %>
  </div>
  <div class="field">
    <%= f.label :q20 %>
    <%= f.select :q20, options_for_select([["E", "E"], ["B", "B"],["R", "R"],["M", "M"]]) %>
  </div>
  <div class="field">
    <%= f.label :q21 %>
    <%= f.select :q21, options_for_select([["E", "E"], ["B", "B"],["R", "R"],["M", "M"]]) %>
  </div>
  <div class="field">
    <%= f.label :q22 %>
    <%= f.select :q22, options_for_select([["E", "E"], ["B", "B"],["R", "R"],["M", "M"]]) %>
  </div>
  <div class="field">
    <%= f.label :q23 %>
    <%= f.select :q23, options_for_select([["E", "E"], ["B", "B"],["R", "R"],["M", "M"]]) %>
  </div>
  <div class="field">
    <%= f.label :q24 %>
    <%= f.select :q24, options_for_select([["E", "E"], ["B", "B"],["R", "R"],["M", "M"]]) %>
  </div>
  <div class="field">
    <%= f.label :q25 %>
    <%= f.select :q25, options_for_select([["E", "E"], ["B", "B"],["R", "R"],["M", "M"]]) %>
  </div>
  <div class="field">
    <%= f.label :q26 %>
    <%= f.select :q26, options_for_select([["E", "E"], ["B", "B"],["R", "R"],["M", "M"]]) %>
  </div>
  <div class="field">
    <%= f.label :q27 %>
    <%= f.select :q27, options_for_select([["E", "E"], ["B", "B"],["R", "R"],["M", "M"]]) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ques/edit.html.erb
<h1>Editing que</h1>

<%= render 'form' %>

<%= link_to 'Show', @que %> |
<%= link_to 'Back', ques_path %>

app/views/ques/index.html.erb
<% if @permitido=="y"%>
  


<h1>Listing ques</h1>
<table>
  <thead>
    <tr>
      <th>Type</th>
      <th>q1</th>
      <th>q2</th>
      <th>q3</th>
      <th>q4</th>
      <th>q5</th>
      <th>q6</th>
      <th>q7</th>
      <th>q8</th>
      <th>q9</th>
      <th>q10</th>
      <th>q11</th>
      <th>q12</th>
      <th>q13</th>
      <th>q14</th>
      <th>q15</th>
      <th>q16</th>
      <th>q17</th>
      <th>q18</th>
      <th>q19</th>
      <th>q20</th>
      <th>q21</th>
      <th>q22</th>
      <th>q23</th>
      <th>q24</th>
      <th>q25</th>
      <th>q26</th>
      <th>q27</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ques.each do |que| %>
      <tr>
        <td><%= que.type %></td>
        <td><%= que.q1 %></td>
        <td><%= que.q2 %></td>
        <td><%= que.q3 %></td>
        <td><%= que.q4 %></td>
        <td><%= que.q5 %></td>
        <td><%= que.q6 %></td>
        <td><%= que.q7 %></td>
        <td><%= que.q8 %></td>
        <td><%= que.q9 %></td>
        <td><%= que.q10 %></td>
        <td><%= que.q11 %></td>
        <td><%= que.q12 %></td>
        <td><%= que.q13 %></td>
        <td><%= que.q14 %></td>
        <td><%= que.q15 %></td>
        <td><%= que.q16 %></td>
        <td><%= que.q17 %></td>
        <td><%= que.q18 %></td>
        <td><%= que.q19 %></td>
        <td><%= que.q20 %></td>
        <td><%= que.q21 %></td>
        <td><%= que.q22 %></td>
        <td><%= que.q23 %></td>
        <td><%= que.q24 %></td>
        <td><%= que.q25 %></td>
        <td><%= que.q26 %></td>
        <td><%= que.q27 %></td>
        <td><%= link_to 'Show', que %></td>
        <td><%= link_to 'Edit', edit_que_path(que) %></td>
        <td><%= link_to 'Destroy', que, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New que', new_que_path %>

<%elsif @permitido=="n"%>

<h2>Lo sentimos: Este formulario solo puede ser accedido desde la universidad</h3>
<br>
<h1>Gracias.</h2>
  

<%end%>

app/views/ques/new.html.erb
<h1>New que</h1>

<%= render 'form' %>

<%= link_to 'Back', ques_path %>

app/views/ques/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_que_path(@que) %> |
<%= link_to 'Back', ques_path %>