config/routes.rb
Rails.application.routes.draw do
  resources :ques

  resources :questionnaires

  resources :courses

  devise_for :users

  resources :aspects

  get 'principal/index'

  resources :survey_types

  resources :surveys

  resources :questions

  resources :users

  root 'principal#index'

  get 'load_user' => 'load_user#index'

  post 'load_user' => 'load_user#load_data'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.has_role? "Admin"
      can :manage, [Survey, SurveyType, Aspect, Question, Course, User]
    elsif user.has_role? "Student"
    	can [:update, :read], Questionnaire
    elsif user.has_role? "Teacher"
        
    elsif user.has_role? "Dean"
    	can :manage, [Survey, SurveyType, Aspect, Question]
      can [:update, :read], User
    elsif user.has_role? "Director"
      
      can [:update, :read], Questionnaire
    end
    
  end
end

app/models/answer.rb
class Answer
  include Mongoid::Document
  include Mongoid::Timestamps

  field :answerField, type: String

  #validates_inclusion_of :answerField, :in => ["E", "B", "R", "M"]

  belongs_to :question

end

app/models/answer_form.rb
class AnswerForm
  include Mongoid::Document
  include Mongoid::Timestamps

  resourcify

  field :details, type: String

  has_and_belongs_to_many :users
  belongs_to :survey
  belongs_to :course

  #attr_accessor :survey
  accepts_nested_attributes_for :survey
	
end

app/models/aspect.rb
class Aspect
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Slug

  resourcify

  field :name, type: String

  validates_uniqueness_of :name
  validates_presence_of :name

  has_many :questions

  slug :name, :history => true
  
end

app/models/course.rb
class Course
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Slug

  resourcify
  
  field :name, type: String
  field :course_id, type: String
  field :group, type: String
  field :faculty, type: String
  field :year, type: String
  field :semester, type: String

  validates_uniqueness_of :course_id, :scope => [:group, :year, :semester]
  has_and_belongs_to_many :users
  has_many :questionnaires

  slug history: true do |curs|
    "#{curs.course_id} #{curs.group}".to_url
  end

end

app/models/que.rb
class Que
  include Mongoid::Document
  field :type, type: String
  field :q1, type: String
  field :q2, type: String
  field :q3, type: String
  field :q4, type: String
  field :q5, type: String
  field :q6, type: String
  field :q7, type: String
  field :q8, type: String
  field :q9, type: String
  field :q10, type: String
  field :q11, type: String
  field :q12, type: String
  field :q13, type: String
  field :q14, type: String
  field :q15, type: String
  field :q16, type: String
  field :q17, type: String
  field :q18, type: String
  field :q19, type: String
  field :q20, type: String
  field :q21, type: String
  field :q22, type: String
  field :q23, type: String
  field :q24, type: String
  field :q25, type: String
  field :q26, type: String
  field :q27, type: String

  field :totalScore, type: String
  field :knowledge, type: String
  field :methodology, type: String
  field :bonds, type: String
  field :labors, type: String
end

app/models/question.rb
class Question
  include Mongoid::Document
  include Mongoid::Timestamps

  resourcify

  field :item, type: String

  #validates_uniqueness_of :item, :scope => :aspect_id
  #validates_presence_of :item, :aspect
  
  has_many :answers
  belongs_to :aspect
  belongs_to :survey

  accepts_nested_attributes_for :answers

end

app/models/questionnaire.rb
class Questionnaire
  include Mongoid::Document
  include Mongoid::Timestamps

  resourcify

  field :detail, type: String

  has_and_belongs_to_many :users
  belongs_to :survey
  belongs_to :course

  #attr_accessor :survey
  accepts_nested_attributes_for :survey
  
end

app/models/role.rb
class Role
  include Mongoid::Document
  has_and_belongs_to_many :users
  belongs_to :resource, :polymorphic => true
  
  field :name, :type => String

  index({
    :name => 1,
    :resource_type => 1,
    :resource_id => 1
  },
  { :unique => true})
  
  scopify
end

app/models/survey.rb
class Survey
  include Mongoid::Document
  include Mongoid::Timestamps

  resourcify
  
  field :name, type: String
  field :active, type: Boolean, default: true

	validates_uniqueness_of :name, :scope => :survey_type_id
	validates_presence_of :name

  has_many :questions
  belongs_to :survey_type
  has_many :questionnaire
  has_and_belongs_to_many :users

	#slug history: true do |surv|
  #  "#{surv.name} #{surv.survey_type.name}".to_url
  #end
  #slug :name, :history => true

  accepts_nested_attributes_for :questions

end

app/models/survey_type.rb
class SurveyType
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Slug

  resourcify

  field :name, type: String

  validates_uniqueness_of :name
  validates_presence_of :name
  
  has_many :surveys

  slug :name, :history => true

end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Slug
  attr_accessor :role
  
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, 
         :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :name,               type: String
  field :id_number,           type: String
  
  #Si es estudiante aquí se almacena el codigo
  #Si es profesor aquí se almacena la cedula

  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String

  has_and_belongs_to_many :courses
  has_and_belongs_to_many :questionnaires

  slug :id_number, :history => true

  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time
end

app/helpers/aspects_helper.rb
module AspectsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/load_user_helper.rb
module LoadUserHelper
end

app/helpers/principal_helper.rb
module PrincipalHelper
end

app/helpers/ques_helper.rb
module QuesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/answer_forms/_form.html.erb
<%= form_for @answer_form, :html => { :class => 'form-horizontal' } do |f| %>

  <strong><%= label_tag "Teacher " %></strong> 
  <%= User.find(@answer_form.user_ids.first).name %>
  <br><br>

  <%= f.fields_for :survey do |builder| %>
    <%= render 'survey_fields', f: builder %>
  <% end %>

  <div class="control-group">
    <%= f.label :details, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :details, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                answer_forms_path, :class => 'btn' %>
  </div>
<% end %>

app/views/answer_forms/edit.html.erb
<%- model_class = AnswerForm -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => "shared/breadcrumbs" %>
<%= render :partial => 'form' %>

app/views/answer_forms/index.html.erb
<%- model_class = AnswerForm -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<%= render :partial => "shared/breadcrumbs" %>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:course) %></th>
      <th><%= model_class.human_attribute_name(:teacher) %></th>
      <th><%= model_class.human_attribute_name(:survey) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @answer_forms.where(user_ids: current_user.id).each do |answer_form| %>
      <tr>
        <td><%= answer_form.course.name %></td>
        <% answer_form.user_ids.each do |user| %>
          <% if JSON.parse(User.find(user).roles.to_json)[0]["name"] == "Teacher" %>
            <td><%= User.find(user).name %></td>
          <% end %>
        <% end %>
        <td><%= answer_form.survey_id %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_answer_form_path(answer_form), :class => 'btn btn-mini' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/answer_forms/new.html.erb
<%- model_class = AnswerForm -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => "shared/breadcrumbs" %>
<%= render :partial => 'form' %>

app/views/answer_forms/show.html.erb
<%- model_class = AnswerForm -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => "shared/breadcrumbs" %>
<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:details) %>:</strong></dt>
  <dd><%= @answer_form.details %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              answer_forms_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_answer_form_path(@answer_form), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              answer_form_path(@answer_form),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/shared/_breadcrumbs.html.erb
<% if @breadcrumbs %>
  <ol class="breadcrumb">
    <% @separator = "/" %>
  <% @breadcrumbs[0..-2].each do |txt, path| %>
    <li>
    <%= link_to t(h(txt)), path %> 
    </li>
    <div id="separador">
    <%= @separator %>
    </div>
  <% end %>
  <li class="active">
  <%= t(h(@breadcrumbs.last.first)) %>
  </li>
  </ol>
<% end %>